"""initial migration: create users and tasks tables

Revision ID: c48ba48a3ca1
Revises: fee5a0790a8d
Create Date: 2026-04-07 07:49:29.338569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48ba48a3ca1'
down_revision: Union[str, None] = 'fee5a0790a8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
